name: Update Data

on:
  schedule:
    - cron:  '0 0 * * 1' # every monday 0:00
  workflow_dispatch:

jobs:
  update-json:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Update JSON
        run: |
          python update_json.py
      - name: Commit and push if changed
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json" || exit 0
          git push